version: '2'

services:
  # Web server
  nginx:
    image: wonderfall/nginx
    container_name: nginx
    depends_on:
      - gogs
      - ghost
      - postfixadmin
      - rainloop
      - selfoss
    ports:
      - "80:8000"
      - "443:4430"
    volumes:
      - /mnt/docker/nginx/sites-enabled:/sites-enabled
      - /mnt/docker/nginx/conf:/conf.d
      - /mnt/docker/nginx/log:/var/log/nginx
      - /mnt/docker/nginx/certs:/certs
    networks:
      - proxy

  # Blog
  ghost:
    image: wonderfall/ghost
    container_name: ghost
    environment:
      - DOMAIN=domain.tdl
    volumes:
      - /mnt/docker/ghost:/ghost/content
    depends_on:
      - mariadb
    networks:
      - db
      - proxy
  
  # Git
  gogs:
    image: gogs/gogs
    container_name: gogs
    volumes:
      - /mnt/docker/gogs:/data
    depends_on:
      - mariadb
    networks:
      - db
      - proxy

  # RSS
  selfoss:
    image: arckosfr/selfoss
    container_name: selfoss
    volumes:
      - /mnt/docker/selfoss:/var/www/html/data
    depends_on:
      - mariadb
    networks:
      - db
      - proxy
  
  # Database
  mariadb:
    image: mariadb:10.1
    container_name: mariadb
    # Info : These variables are ignored when the volume already exists (databases created before).
    environment:
      - MYSQL_ROOT_PASSWORD=xxxxx
      - MYSQL_DATABASE=postfix
      - MYSQL_USER=postfix
      - MYSQL_PASSWORD=xxxxx
    volumes:
      - /mnt/docker/mysql/db:/var/lib/mysql
    networks:
      - db

  mailserver:
    image: hardware/mailserver
    container_name: mailserver
    domainname: domain.tdl                # Mail server FQDN & reverse = mail.domain.tld.
    hostname: mail
    ports:
      - "25:25"     # SMTP                - Required
    # - "110:110"   # POP3       STARTTLS - Optional - For webmails/desktop clients
      - "143:143"   # IMAP       STARTTLS - Optional - For webmails/desktop clients
    # - "465:465"   # SMTPS      SSL/TLS  - Optional - Enabled for compatibility reason, otherwise disabled
      - "587:587"   # Submission STARTTLS - Optional - For webmails/desktop clients
      - "993:993"   # IMAPS      SSL/TLS  - Optional - For webmails/desktop clients
    # - "995:995"   # POP3S      SSL/TLS  - Optional - For webmails/desktop clients
      - "4190:4190" # SIEVE      STARTTLS - Optional - Recommended for mail filtering
    environment:
      - DBPASS=xxxxx
    # - ENABLE_POP3=true          # Enable POP3 protocol
    # - ENABLE_POSTGREY=true      # Enable greylisting policy server
    # - DISABLE_CLAMAV=true       # Disable virus scanning
    # - DISABLE_SPAMASSASSIN=true # Disable SPAM checking
    # - DISABLE_SIEVE=true        # Disable ManageSieve protocol
    volumes:
      - /mnt/docker/mail:/var/mail
      - /mnt/docker/opendkim:/etc/opendkim/keys
    networks:
      - db

  # Control panel
  postfixadmin:
    image: hardware/postfixadmin
    container_name: postfixadmin
    domainname: domain.tdl
    hostname: mail
    depends_on:
      - mariadb
      - mailserver
    environment:
      - DBPASS=xxxxx
    networks:
      - db
      - proxy

  # Webmail
  rainloop:
    image: hardware/rainloop
    container_name: rainloop
    depends_on:
      - mailserver
      - mariadb
    volumes:
      - /mnt/docker/rainloop:/rainloop/data
    networks:
      - db
      - proxy

networks:
  proxy:
  db: